---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Пользователь должен иметь возможность переключить язык интерфейса
  - Сайт должен иметь локализацию (перевод) на русский и английский языки
  - На странице товара и в каталоге должны выводиться название, рейтинг, цена со скидкой и без нее
implicit:
  - Система должна загружать домашнюю страницу менее чем за 3 секунды
  - Система должна корректно обрабатывать запросы сервера
  - Пользователь должен иметь возможность добавлять товар в корзину и одновременно с этим продолжать выбирать товары в каталоге
  - Пользователь должен иметь возможность оформить заказ
  - Пользователь должен иметь возможность оформить заказ с переходом на страницу оплаты
  - Пользователь должен иметь возможность удалить товары из корзины
  - Корзина должна храниться в сессии браузера
  - Пользователь должен иметь возможность просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом (т.е интернет-магазин должен быть SPA-приложением)
